### ISSUE TITLE
File retrieval

### ISSUE THREAD

**Issue by ryleyw** [VikeLabs/lecshare-api#1]
For a given course name and lecture number, should respond with the .json file and audio file.

Milestones
- [x] Transcription
- [x] Audio

**Comment by aomi** [comment]
Given your current credentials, try grabbing the .json from the S3 bucket rather than a local file. Your given AWS credentials allow you to list objects within the bucket, download objects etc. No write access.
s3://assets-lecshare.oimo.ca/vikelabs_test1.json is the resource (format might be different for the link)
