### ISSUE TITLE
File storage and access?

### ISSUE THREAD

**Issue by malcolmseyd** [VikeLabs/lecshare-api#11]
I'd like to start working on #1 File Retrieval but I don't know how we're planning on working with files. What will be the methods of file storage and access?

**Comment by aomi** [comment]
Amazon S3 for storage.

**Comment by aomi** [comment]
Given your current credentials, try grabbing the `.json` from the S3 bucket rather than a local file. Your given AWS credentials allow you to list objects within the bucket, download objects etc. No write access. 
`s3://assets-lecshare.oimo.ca/vikelabs_test1.json` is the resource (format might be different for the link)
